name: Deploy ADF Monitor Pro

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_webapp.txt || pip install streamlit plotly pandas requests
    
    - name: Test application import
      run: |
        python -c "import streamlit; print('Streamlit installed successfully')"

  deploy-pages:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create documentation site
      run: |
        mkdir -p static_site
        echo '<!DOCTYPE html><html><head><title>ADF Monitor Pro</title></head><body><h1>ADF Monitor Pro</h1><p>Enterprise Azure Data Factory Monitoring Platform</p><h2>Quick Start</h2><p>Launch in GitHub Codespaces for instant access!</p></body></html>' > static_site/index.html
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './static_site'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2