name: Deploy ADF Monitor Pro

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_webapp.txt || pip install streamlit plotly pandas requests
    
    - name: Test application import
      run: |
        python -c "import streamlit; print('Streamlit installed successfully')"

  deploy-pages:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create documentation site
      run: |
        mkdir -p static_site
        cat > static_site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>ADF Monitor Pro - Enterprise Azure Data Factory Monitoring</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #333; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; }
                .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
                .header { text-align: center; color: white; margin-bottom: 50px; padding: 40px 0; }
                .title { font-size: 3.5em; font-weight: 700; margin-bottom: 20px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); }
                .subtitle { font-size: 1.3em; opacity: 0.9; }
                .card { background: white; border-radius: 15px; padding: 30px; margin: 20px 0; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
                .features { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin: 40px 0; }
                .feature { background: white; padding: 25px; border-radius: 10px; text-align: center; box-shadow: 0 5px 15px rgba(0,0,0,0.1); }
                .feature h3 { color: #667eea; margin-bottom: 15px; font-size: 1.3em; }
                .cta { text-align: center; margin: 40px 0; }
                .btn { display: inline-block; padding: 15px 30px; margin: 10px; background: #667eea; color: white; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 1.1em; transition: all 0.3s ease; }
                .btn:hover { background: #5a6fd8; transform: translateY(-2px); box-shadow: 0 5px 15px rgba(0,0,0,0.2); }
                .btn-secondary { background: #764ba2; }
                .btn-secondary:hover { background: #6a4190; }
                .emoji { font-size: 2em; margin-bottom: 15px; display: block; }
                .footer { text-align: center; color: white; margin-top: 50px; opacity: 0.8; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1 class="title">🏭 ADF Monitor Pro</h1>
                    <p class="subtitle">Enterprise Azure Data Factory Monitoring & Automation Platform</p>
                </div>
                
                <div class="card">
                    <div class="cta">
                        <h2>🚀 Get Started in Seconds</h2>
                        <p>Choose your preferred way to run ADF Monitor Pro:</p>
                        <a href="https://codespaces.new/SasidharPV/AIMS" class="btn">☁️ Launch in Codespaces</a>
                        <a href="https://github.com/SasidharPV/AIMS" class="btn btn-secondary">📁 View Repository</a>
                    </div>
                </div>
                
                <div class="features">
                    <div class="feature">
                        <span class="emoji">🤖</span>
                        <h3>AI-Powered Analysis</h3>
                        <p>Intelligent error classification and automated retry recommendations using multiple AI providers (OpenAI, Azure OpenAI, Google Gemini, Anthropic).</p>
                    </div>
                    <div class="feature">
                        <span class="emoji">📊</span>
                        <h3>Enterprise Dashboard</h3>
                        <p>Professional Streamlit web interface with real-time monitoring, interactive charts, and comprehensive KPIs.</p>
                    </div>
                    <div class="feature">
                        <span class="emoji">⚙️</span>
                        <h3>Complete Admin Interface</h3>
                        <p>5-tab configuration system for Azure setup, AI providers, environments, notifications, and security - all through the UI!</p>
                    </div>
                    <div class="feature">
                        <span class="emoji">🌍</span>
                        <h3>Multi-Environment</h3>
                        <p>Seamlessly monitor Production, Staging, and Development environments with environment-specific configurations.</p>
                    </div>
                    <div class="feature">
                        <span class="emoji">🔔</span>
                        <h3>Smart Notifications</h3>
                        <p>Multi-channel alerts via Teams, Slack, Email, and SMS with intelligent filtering and escalation rules.</p>
                    </div>
                    <div class="feature">
                        <span class="emoji">🔒</span>
                        <h3>Enterprise Security</h3>
                        <p>Service principal authentication, role-based access control, and comprehensive audit logging.</p>
                    </div>
                </div>
                
                <div class="card">
                    <h2>🚀 Quick Start Options</h2>
                    <h3>GitHub Codespaces (Recommended)</h3>
                    <ol>
                        <li>Click the "Launch in Codespaces" button above</li>
                        <li>Wait for environment setup (2-3 minutes)</li>
                        <li>Run: <code>python startup.py webapp</code></li>
                        <li>Access via forwarded port 8501</li>
                    </ol>
                    
                    <h3>Local Installation</h3>
                    <pre>git clone https://github.com/SasidharPV/AIMS.git
        cd AIMS
        pip install -r requirements_webapp.txt
        python startup.py webapp</pre>
                </div>
                
                <div class="footer">
                    <p>🏭 ADF Monitor Pro - Powered by AI • Built for Scale • Designed for DevOps Teams</p>
                    <p>⭐ Star us on <a href="https://github.com/SasidharPV/AIMS" style="color: white;">GitHub</a></p>
                </div>
            </div>
        </body>
        </html>
        EOF
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './static_site'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4